import type {
  GoldenPathDomainDefinition,
  GoldenPathPathProjection,
  GoldenPathSkillDefinition,
} from "./types";

export const GOLDEN_PATH_DOMAINS: GoldenPathDomainDefinition[] = [
  {
    id: "product",
    name: "产品判断",
    description: "理解问题、用户和价值主张。",
    adjacentDomainIds: ["ai-systems", "growth"],
  },
  {
    id: "frontend",
    name: "前端体验",
    description: "构建清晰、顺滑、可迭代的用户界面。",
    adjacentDomainIds: ["backend", "ai-systems"],
  },
  {
    id: "backend",
    name: "系统与数据",
    description: "处理接口、数据建模、鉴权和持久化。",
    adjacentDomainIds: ["frontend", "delivery", "data"],
  },
  {
    id: "ai-systems",
    name: "AI 应用架构",
    description: "设计模型交互、上下文、工具和工作流。",
    adjacentDomainIds: ["product", "frontend", "automation"],
  },
  {
    id: "data",
    name: "数据分析",
    description: "用 SQL、Python、统计和可视化建立判断。",
    adjacentDomainIds: ["backend", "growth", "product"],
  },
  {
    id: "automation",
    name: "自动化杠杆",
    description: "借助工作流、工具和智能体提升交付效率。",
    adjacentDomainIds: ["ai-systems", "delivery", "growth"],
  },
  {
    id: "growth",
    name: "增长与商业",
    description: "围绕用户获取、反馈和付费形成闭环。",
    adjacentDomainIds: ["product", "data", "automation"],
  },
  {
    id: "delivery",
    name: "交付与运维",
    description: "把系统上线、观测并持续稳定运行。",
    adjacentDomainIds: ["backend", "automation"],
  },
];

export const GOLDEN_PATH_SKILLS: GoldenPathSkillDefinition[] = [
  {
    id: "rapid-prototyping",
    name: "快速原型",
    description: "用最短路径把想法变成可体验的产品。",
    domainIds: ["product", "frontend"],
    tier: "foundation",
    importance: 1,
    aliases: ["快速原型", "prototype", "mvp", "原型"],
  },
  {
    id: "problem-framing",
    name: "问题定义",
    description: "先把问题、用户和目标说清楚。",
    domainIds: ["product"],
    tier: "foundation",
    importance: 1,
    aliases: ["问题定义", "problem framing", "需求分析", "需求拆解"],
  },
  {
    id: "user-research",
    name: "用户研究",
    description: "通过观察、访谈和画像理解用户。",
    domainIds: ["product"],
    tier: "foundation",
    importance: 1,
    aliases: ["用户研究", "user research", "用户访谈", "persona"],
  },
  {
    id: "product-strategy",
    name: "产品策略",
    description: "定义价值主张、边界和成功标准。",
    domainIds: ["product", "growth"],
    tier: "core",
    importance: 1.25,
    aliases: ["产品策略", "product strategy", "产品定位", "价值主张"],
    prerequisites: ["problem-framing", "user-research"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    description: "用类型系统组织复杂产品代码。",
    domainIds: ["frontend", "backend"],
    tier: "foundation",
    importance: 1,
    aliases: ["typescript", "ts", "类型系统"],
  },
  {
    id: "react",
    name: "React",
    description: "掌握现代组件化界面开发方式。",
    domainIds: ["frontend"],
    tier: "foundation",
    importance: 1,
    aliases: ["react", "jsx", "hooks", "组件"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    description: "用现代全栈框架完成产品骨架。",
    domainIds: ["frontend", "backend"],
    tier: "core",
    importance: 1.2,
    aliases: ["next.js", "nextjs", "app router", "route handler"],
    prerequisites: ["typescript", "react"],
  },
  {
    id: "api-design",
    name: "API 设计",
    description: "定义稳定接口与错误契约。",
    domainIds: ["backend"],
    tier: "core",
    importance: 1.1,
    aliases: ["api", "接口设计", "rest api", "server action"],
    prerequisites: ["typescript"],
  },
  {
    id: "database-modeling",
    name: "数据库建模",
    description: "设计数据结构、关系和查询模式。",
    domainIds: ["backend", "data"],
    tier: "core",
    importance: 1.2,
    aliases: ["postgres", "sql", "数据库", "drizzle", "schema"],
    prerequisites: ["api-design"],
  },
  {
    id: "llm-architecture",
    name: "LLM 应用架构",
    description: "设计模型、上下文、工具与流式体验。",
    domainIds: ["ai-systems", "backend"],
    tier: "core",
    importance: 1.35,
    aliases: ["llm", "AI SDK", "streamText", "rag", "tool call", "agent"],
    prerequisites: ["nextjs", "api-design"],
  },
  {
    id: "prompt-engineering",
    name: "Prompt Engineering",
    description: "让模型更稳定地完成目标任务。",
    domainIds: ["ai-systems", "product"],
    tier: "core",
    importance: 1.1,
    aliases: ["prompt", "prompt engineering", "提示工程", "提示词"],
    prerequisites: ["llm-architecture"],
  },
  {
    id: "ai-evaluation",
    name: "AI 评测",
    description: "定义质量门槛、评测集和回归机制。",
    domainIds: ["ai-systems", "data"],
    tier: "advanced",
    importance: 1.15,
    aliases: ["eval", "评测", "质量评估", "回归测试"],
    prerequisites: ["llm-architecture"],
  },
  {
    id: "automation-workflows",
    name: "自动化工作流",
    description: "把工具、事件和任务链路编排起来。",
    domainIds: ["automation", "ai-systems"],
    tier: "core",
    importance: 1.1,
    aliases: ["automation", "workflow", "webhook", "agent tool", "n8n"],
    prerequisites: ["llm-architecture"],
  },
  {
    id: "delivery-observability",
    name: "部署与观测",
    description: "完成部署、回滚、日志与降级治理。",
    domainIds: ["delivery", "backend"],
    tier: "advanced",
    importance: 1.15,
    aliases: ["docker", "部署", "observability", "日志", "监控", "ci"],
    prerequisites: ["database-modeling", "llm-architecture"],
  },
  {
    id: "sql",
    name: "SQL",
    description: "完成提取、聚合和分析查询。",
    domainIds: ["data", "backend"],
    tier: "foundation",
    importance: 1,
    aliases: ["sql", "postgres", "mysql", "查询"],
  },
  {
    id: "python-analysis",
    name: "Python 分析",
    description: "用 Python 进行清洗、探索与建模。",
    domainIds: ["data"],
    tier: "foundation",
    importance: 1,
    aliases: ["python", "pandas", "jupyter", "数据处理"],
  },
  {
    id: "statistics",
    name: "统计与实验",
    description: "理解显著性、实验设计与可信判断。",
    domainIds: ["data", "growth"],
    tier: "core",
    importance: 1.15,
    aliases: ["统计", "statistics", "实验设计", "ab test", "假设检验"],
    prerequisites: ["sql", "python-analysis"],
  },
  {
    id: "visualization",
    name: "可视化表达",
    description: "把数据讲成可执行结论。",
    domainIds: ["data", "growth"],
    tier: "core",
    importance: 1.05,
    aliases: ["可视化", "dashboard", "tableau", "power bi", "图表"],
    prerequisites: ["sql"],
  },
  {
    id: "business-analysis",
    name: "业务分析",
    description: "围绕留存、转化和增长解释数据。",
    domainIds: ["data", "growth", "product"],
    tier: "core",
    importance: 1.2,
    aliases: ["业务分析", "增长分析", "漏斗", "留存", "转化"],
    prerequisites: ["sql"],
  },
  {
    id: "launch-growth",
    name: "分发增长",
    description: "找到第一批用户并形成持续反馈。",
    domainIds: ["growth", "product"],
    tier: "core",
    importance: 1.1,
    aliases: ["增长", "分发", "用户获取", "内容增长", "冷启动"],
    prerequisites: ["product-strategy"],
  },
  {
    id: "monetization",
    name: "商业化设计",
    description: "设计付费方式、服务边界与交付模式。",
    domainIds: ["growth", "product"],
    tier: "advanced",
    importance: 1.15,
    aliases: ["商业化", "付费", "定价", "订阅", "monetization"],
    prerequisites: ["launch-growth", "product-strategy"],
  },
];

export const GOLDEN_PATH_SKILL_IDS = GOLDEN_PATH_SKILLS.map((skill) => skill.id) as [
  string,
  ...string[],
];

export const GOLDEN_PATH_PROJECTION_PRIORS: GoldenPathPathProjection[] = [
  {
    id: "ai-product-track",
    name: "AI 产品主线",
    tagline: "围绕用户问题、AI 能力和增长结果组织学习。",
    description: "适合正在把产品判断、AI 方案设计和实验验证串成一条主线的人。",
    outcomes: ["AI 产品设计", "需求分析", "实验增长"],
    domainIds: ["product", "ai-systems", "growth"],
    skillIds: [
      "problem-framing",
      "user-research",
      "product-strategy",
      "prompt-engineering",
      "ai-evaluation",
      "business-analysis",
      "launch-growth",
      "monetization",
    ],
  },
  {
    id: "ai-builder-track",
    name: "AI 构建主线",
    tagline: "从界面、接口到模型交互，把 AI 产品真正做出来。",
    description: "适合正在强化前端、后端、AI 架构与上线能力的人。",
    outcomes: ["全栈工程", "AI 应用开发", "部署交付"],
    domainIds: ["frontend", "backend", "ai-systems", "delivery"],
    skillIds: [
      "typescript",
      "react",
      "nextjs",
      "api-design",
      "database-modeling",
      "llm-architecture",
      "prompt-engineering",
      "automation-workflows",
      "delivery-observability",
    ],
  },
  {
    id: "data-growth-track",
    name: "数据洞察主线",
    tagline: "用数据、实验和表达能力驱动判断。",
    description: "适合正在从分析、实验到可视化表达建立决策能力的人。",
    outcomes: ["数据分析", "实验设计", "业务洞察"],
    domainIds: ["data", "growth", "product"],
    skillIds: [
      "sql",
      "python-analysis",
      "statistics",
      "visualization",
      "business-analysis",
      "launch-growth",
    ],
  },
  {
    id: "indie-maker-track",
    name: "独立构建主线",
    tagline: "把机会判断、快速构建、分发与商业闭环合成一条线。",
    description: "适合正在从个人项目、AI 工具到小产品验证形成闭环的人。",
    outcomes: ["独立产品验证", "自动化业务", "增长试验"],
    domainIds: ["product", "automation", "growth", "ai-systems"],
    skillIds: [
      "problem-framing",
      "product-strategy",
      "rapid-prototyping",
      "automation-workflows",
      "llm-architecture",
      "launch-growth",
      "monetization",
    ],
  },
];
