export const CAREER_TREE_SCHEMA_VERSION = 1;
export const CAREER_PROJECTION_SCHEMA_VERSION = 1;
export const GROWTH_AI_MODEL_LABEL = "GROWTH_AI_JSON";
export const GROWTH_EXTRACT_PROMPT_VERSION = "growth-extract@v3";
export const GROWTH_MERGE_PROMPT_VERSION = "growth-merge-deterministic@v1";
export const GROWTH_MERGE_RUNTIME_LABEL = "DETERMINISTIC_GROWTH_MERGE";
export const GROWTH_COMPOSE_MODEL_LABEL = "GROWTH_AI_COMPOSE_PIPELINE";
export const GROWTH_COMPOSE_METADATA_MODEL_LABEL = "GROWTH_AI_DIRECTION_METADATA_JSON";
export const GROWTH_COMPOSE_PROMPT_VERSION = "growth-compose@v16";
export const GROWTH_COMPOSE_METADATA_PROMPT_VERSION = "growth-compose-metadata@v10";
export const GROWTH_PROJECTION_RUNTIME_LABEL = "DETERMINISTIC_GROWTH_PROJECTION";
export const GROWTH_EXTRACT_AI_TIMEOUT_MS = 90_000;
export const GROWTH_DIRECTION_METADATA_AI_TIMEOUT_MS = 25_000;

export const MASTERED_PROGRESS_THRESHOLD = 80;
export const MASTERED_EVIDENCE_THRESHOLD = 60;
export const IN_PROGRESS_THRESHOLD = 30;
export const READY_PREREQ_PROGRESS_THRESHOLD = 50;
