export const CAREER_TREE_SCHEMA_VERSION = 1;
export const CAREER_PROJECTION_SCHEMA_VERSION = 1;
export const GROWTH_AI_MODEL_LABEL = "GROWTH_AI_JSON";
export const GROWTH_COMPOSE_RUNTIME_LABEL = "DETERMINISTIC_GROWTH_COMPOSE";
export const GROWTH_PROJECTION_RUNTIME_LABEL = "DETERMINISTIC_GROWTH_PROJECTION";
export const GROWTH_STRUCTURED_AI_TIMEOUT_MS = 90_000;

export const MASTERED_PROGRESS_THRESHOLD = 80;
export const MASTERED_EVIDENCE_THRESHOLD = 60;
export const IN_PROGRESS_THRESHOLD = 30;
export const READY_PREREQ_PROGRESS_THRESHOLD = 50;

export const DEFAULT_EMPTY_SNAPSHOT_STATUS = "empty";
export const DEFAULT_PENDING_SNAPSHOT_STATUS = "pending";
