export const CAREER_TREE_SCHEMA_VERSION = 3;
export const CAREER_TREE_EXTRACT_PROMPT_VERSION = "career-tree-extract@v2";
export const CAREER_TREE_MERGE_PROMPT_VERSION = "career-tree-merge@v1";
export const CAREER_TREE_COMPOSE_PROMPT_VERSION = "career-tree-compose@v5";

export const CAREER_TREE_EXTRACT_TIMEOUT_MS = 90_000;
export const CAREER_TREE_MERGE_TIMEOUT_MS = 90_000;
export const CAREER_TREE_COMPOSE_TIMEOUT_MS = 180_000;

export const MAX_CAREER_EVIDENCE_ITEMS_PER_COURSE = 32;
export const MAX_CAREER_NEW_NODES_PER_COURSE = 18;
export const MAX_CAREER_MERGE_EDGES_PER_COURSE = 36;
export const MAX_CAREER_TREES = 5;

export const CAREER_COMPLETED_PROGRESS_THRESHOLD = 100;
export const CAREER_IN_PROGRESS_THRESHOLD = 30;
export const CAREER_READY_PREREQ_PROGRESS_THRESHOLD = 40;
