export const CAREER_TREE_SCHEMA_VERSION = 1;

export const MASTERED_PROGRESS_THRESHOLD = 80;
export const MASTERED_EVIDENCE_THRESHOLD = 60;
export const IN_PROGRESS_THRESHOLD = 30;
export const READY_PREREQ_PROGRESS_THRESHOLD = 50;

export const DEFAULT_EMPTY_SNAPSHOT_STATUS = "empty";
export const DEFAULT_PENDING_SNAPSHOT_STATUS = "pending";
